version: "3.8"

services:
  porthub:
    build: .
    container_name: porthub
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/systemd:/run/systemd:ro
      - ./config:/app/config
    network_mode: host
